### ISSUE TITLE
send token in header.

### ISSUE THREAD

**Issue by mrdsn3** [khoih-prog/WebSockets2_Generic#13]
I have  problem can anyone help me? how to connect web socket server, while connecting I need to send token (already generated JSON token) in header.

**Comment by mrdsn3** [comment]
How i can add token in header of websocket client

**Comment by khoih-prog** [comment]
Closed due to long-time inactivity and issue was asked and answered/solved in [**How i can add token in header of websocket client** #621](https://github.com/Links2004/arduinoWebSockets/issues/621)
