### ISSUE TITLE
WebSocket doesn't connect without a CA certificate.

### ISSUE THREAD

**Issue by anand-010** [khoih-prog/WebSockets2_Generic#17]
I am using NodeMcu 32s with WebSockets2_Generic v1.1.0
As per the documentation CA cert is not necessary.
![3](https://user-images.githubusercontent.com/32414977/114965289-f0a73780-9e8d-11eb-9346-055dbff38591.PNG)
But I can't find a way to connect without a CA cert.
In my [previous library](https://github.com/Links2004/arduinoWebSockets) for Esp 8266 it works without a CA cert.
but it not provide this feature for Esp32.

I need a persistent connection without worry about CA cert validity.

**Comment by khoih-prog** [comment]
ESP32 is different from ESP8266. I only provide standard support to using SSL Cert.
You have to go to other library so.
