### ISSUE TITLE
MKR1000 and socket.io

### ISSUE THREAD

**Issue by Josua2012** [khoih-prog/WebSockets2_Generic#19]
Hello,

Can your library be used to communicate with a websocket server created with nodejs + express + **socket.io**?
Can it simultaneously be used to call a rest api made with nodejs + express?
Do you have examples using rest api?
Can it be used with a MKR1000 and Wifi101?
Do you have examples using Wifi101?

Thank you very much for all your information.

Regards,

**Comment by khoih-prog** [comment]
Hi,

You have first start to read to see it the board is supported, then if yes, test compile to see of OK before posting any question.

Anyway, it's compile OK with MKR1000 using WiFiNINA. So, it'll work with WiFi101 (possibly need some minor changes, if there is issue)

![Selection_808](https://user-images.githubusercontent.com/57012152/118917997-07fb9980-b900-11eb-9085-06bcd21fff46.png)

All other questions, it's **up to you** to find out the solution. **I wish I have all the time in the world** to research and find the answers for everybody. 

So you have spend some time to do the research yourself.

This is only for **bug reports** or reasonable **enhancement** requests.

Good Luck,
