### ISSUE TITLE
MKR1000 and WIFI problem and another problem

### ISSUE THREAD

**Issue by Josua2012** [khoih-prog/WebSockets2_Generic#20]
### Describe the bug

I am running the sample program "SAMD-Minimal-Client", but it has a problem when it reaches any WIFI line. 

Arduino IDE 1.8.15
Arduino MKR 1000
Installed libraries:
WiFiNINA_Generic v1.2.4
WebSockets2_Generic v1.8.5

![sc10](https://user-images.githubusercontent.com/1523607/118973644-2c905980-b972-11eb-8e17-ca8ee69d21c1.jpg)

### Steps to Reproduce

When I compile the sample program I get some strange lines before finishing compilation (ScreenShot sc05.jpg).
I have added some lines to the code Serial.prinln ("1") ... (ScreenShot sc06.jpg) to see where the execution of the program goes.
As you will see in the screenshot, on the serial monitor, the program correctly detects my MKR1000, but it does not pass the Serial.print (1) line, that is, it remains blocked in WiFi.status () (ScreenShot sc07.jpg)
Even if you disable several lines in the program prior to the WiFi connection (ScreenShot sc08.jpg), it always stays blocked, even on the WiFi.begin line (ScreenShot sc09.jpg).
You can also see in the screenshots that I have used the firmware check programs and another example program from the Wifi101 library to check the WiFi connection and everything works perfectly (ScreenShots sc01, sc02, sc03, sc04). That is, the problem is when using your library.
Am I doing something wrong or is it a bug in your library? 
Look at all the screenshots. 

![sc05](https://user-images.githubusercontent.com/1523607/118971521-d02c3a80-b96f-11eb-883b-dcfca5743f7f.jpg)
![sc06](https://user-images.githubusercontent.com/1523607/118973081-99572400-b971-11eb-9970-3ae72dfec75a.jpg)
![sc07](https://user-images.githubusercontent.com/1523607/118973106-9e1bd800-b971-11eb-9f65-793034e4ff24.jpg)
![sc08](https://user-images.githubusercontent.com/1523607/118973125-a3792280-b971-11eb-80f7-cf49f6517a66.jpg)
![sc09](https://user-images.githubusercontent.com/1523607/118973152-a8d66d00-b971-11eb-84a3-b639ef937ca1.jpg)

Checks:

**CheckWifi101FirmwareVersion**

![sc01](https://user-images.githubusercontent.com/1523607/118973766-521d6300-b972-11eb-84b8-b2edac16dafc.jpg)
![sc02](https://user-images.githubusercontent.com/1523607/118973780-56498080-b972-11eb-8479-6323e02af4a7.jpg)

**WiFiWebClient**

![sc03](https://user-images.githubusercontent.com/1523607/118973855-6d886e00-b972-11eb-964f-2b09af797b09.jpg)
![sc04](https://user-images.githubusercontent.com/1523607/118973869-71b48b80-b972-11eb-9080-aed3dbb6bf7a.jpg)

Thank you very much for your help. 

Regards,
Jose.

**Comment by khoih-prog** [comment]
This [**WebSockets2_Generic** Library](https://github.com/khoih-prog/WebSockets2_Generic) is **not currently supporting** boards using WiFi101 shield and library.

I already checked and to provide support to this WiFi101 requires **drastic changes** in both [**WebSockets2_Generic** Library](https://github.com/khoih-prog/WebSockets2_Generic) and some changes in [**WiFi101** library](https://github.com/arduino-libraries/WiFi101).

Because of the **unpopularity of WiFi101 as well as MKR1000**, I won't assign this work with high priority. And it'll take **weeks** to fix / update. Moreover, I don't have this combination MKR1000 + WiFi101 to test.

I suggest you, if **urgent**. to use another currently-supported combination, such as **ESP32, ESP8266, Nano-33-IoT, or even MKR1000 with Ethernet W5x00/EN28J60.**

If you're willing to wait, and test within a week or so, I can speed-up the changes for you to test.

Good Luck,

**Comment by Josua2012** [comment]
Hi, 
The problem is that they are mkr1000 arduinos already mounted on a special circuit, so I have no choice but to use this combination. 
Yes, I could wait a week and test your new version. :)

On the server we have a socket.io, express and nodejs configuration.
I have seen that other products support websockets, but not socket.io.
ArduinoWebSockets (https://github.com/Links2004/arduinoWebSockets) supports socket.io, however it does not support the arduino MKR1000. :(
Socket.io is based on the websockets protocol, but it is a modified and improved protocol, although not compatible with the websockets standard. Socket.io is mostly used with Nodejs.
Do you know if your library is prepared for both the websockets protocol and the improved socket.io?

Thank you very much for all your help.

**Comment by khoih-prog** [comment]
You can have a look at my [**WebSockets_Generic** Library](https://github.com/khoih-prog/WebSockets_Generic), based on [**ArduinoWebSockets**](https://github.com/Links2004/arduinoWebSockets) and supporting Socket.IO.

For example [**Generic_WebSocketClientSocketIO_WiFiNINA** example](https://github.com/khoih-prog/WebSockets_Generic/tree/master/examples/Generic/WiFiNINA/Generic_WebSocketClientSocketIO_WiFiNINA).

If OK and you'll spend time to test, I'll add support to MKR1000 and WiFi101 to that [**WebSockets_Generic** Library](https://github.com/khoih-prog/WebSockets_Generic)

**Comment by Josua2012** [comment]
Yes. Of course. I will be doing the test of all the improvements that you are producing to your library. :)
Do you think you can have a preliminary version in 1 week?
Thank you so much for all your help.

**Comment by khoih-prog** [comment]
Will release tomorrow. Almost done

You can test the [**Modified WiFi101** library](https://github.com/khoih-prog/WiFi101) now.

**Comment by Josua2012** [comment]
Do you know if the supported version of socket.io in your library corresponds to the supported version of node socket.io (https://www.npmjs.com/package/socket.io)?

**Comment by Josua2012** [comment]
You are wonderful, you are a crack.  :)
I'm going to do tests.
I will tell you something.

**Comment by khoih-prog** [comment]
No idea yet. Many different implementations out there. But if they stick to the Socket.IO standards, it'll be compatible and OK.

**Comment by Josua2012** [comment]
You have to guide me a bit to do the tests you need to check that everything works correctly.
1) I overwrite the installation of my standard WiFi101 library with yours.
2) I check that the WiFi101 library examples continue to work.
Do you want me to do something else for now?

**Comment by khoih-prog** [comment]
Already publish [**WebSockets2_Generic** Releases v1.3.0](https://github.com/khoih-prog/WebSockets2_Generic/releases/tag/v1.3.0)

Please test with the [**Forked WiFi101** library](https://github.com/khoih-prog/WiFi101) and let me know the result.

Thanks,

---

### Release v1.3.0

1. Add support to WiFi101. To be used with [**Forked WiFi101** library](https://github.com/khoih-prog/WiFi101)
2. Check compatibility with new ESP8266 core v3.0.0
3. Suppress warnings

**Comment by khoih-prog** [comment]
> I overwrite the installation of my standard WiFi101 library with yours.
> I check that the WiFi101 library examples continue to work.
> Do you want me to do something else for now?

Those are enough tests.

**Comment by Josua2012** [comment]
First analysis.
I have overwritten your WiFi101 library on my computer.
I have tried some examples and they still work. :)

With the library manager of the Arduino IDE I have installed your WebSockects_Generic library.
I have modified the Generic_WebSocketClientSocketIO_WiFiNINA example for SAMD21.
Please tell me if I have done this modification correctly or have to do it differently.
When running the example it cannot connect to my WiFi.
Look at the screenshots. 

![sc11](https://user-images.githubusercontent.com/1523607/119098910-aaa63c00-ba16-11eb-9e42-505d9ba0a817.jpg)
![sc12](https://user-images.githubusercontent.com/1523607/119098980-b98cee80-ba16-11eb-8d13-e1e7f6665801.jpg)
![sc13](https://user-images.githubusercontent.com/1523607/119099005-bd207580-ba16-11eb-8efd-f5c872981848.jpg)

Tell me if I should do some other tests. 
Thanks.

**Comment by khoih-prog** [comment]
WebSockects_Generic library is not supporting WiFi101. That;s why you have the same hanging issue because it tries to use WiFiNINA, instead of WiFi101.

Have to fix in next step, if necessary.

**Comment by khoih-prog** [comment]
Now, just try the WebSockects2_Generic with normal WebSocket server, to see of WiFi101 is working OK.

Use the examples such as [**SAMD_WiFi101-Minimal-Client**](https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/Generic/WiFi101/SAMD/SAMD_WiFi101-Minimal-Client).

There are 7 examples

#### For SAMD21/SAMD51 boards using WiFi101

1. [SAMD_WiFi101-Client](https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/Generic/WiFi101/SAMD/SAMD_WiFi101-Client)
2. [SAMD_WiFi101-Minimal-Client](https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/Generic/WiFi101/SAMD/SAMD_WiFi101-Minimal-Client)
3. [SAMD_WiFi101-Client_SINRIC](https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/Generic/WiFi101/SAMD/SAMD_WiFi101-Client_SINRIC)
4. [SAMD_WiFi101-Server](https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/Generic/WiFi101/SAMD/SAMD_WiFi101-Server)
5. [SAMD_WiFi101-RepeatingClient](https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/Generic/WiFi101/SAMD/SAMD_WiFi101-RepeatingClient)
6. [SAMD_WiFi101_ServerAllFunctionsDemo](https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/Generic/WiFi101/SAMD/SAMD_WiFi101_ServerAllFunctionsDemo)
7. [SAMD_WiFi101-AdvancedWebServer](https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/Generic/WiFi101/SAMD/SAMD_WiFi101-AdvancedWebServer).

**Comment by Josua2012** [comment]
In WebSockects2_Generic now the WiFi works perfectly, thank you very much.
In the examples you can modify the lines that show the Local IP so that they show it correctly.
Look at the following screenshots: 

![sc14](https://user-images.githubusercontent.com/1523607/119105340-826e0b80-ba1d-11eb-9a5a-596caf7686b3.jpg)
![sc15](https://user-images.githubusercontent.com/1523607/119105357-869a2900-ba1d-11eb-94ee-bff2d8a5c7ed.jpg)
![sc16](https://user-images.githubusercontent.com/1523607/119105392-8ef26400-ba1d-11eb-8f59-18a866865f67.jpg)

Thank you very much for your work.

**Comment by Josua2012** [comment]
Hi Khoi Hoang,

I have made a small standard websocket server based on the nodejs websocket library (https://www.npmjs.com/package/websocket).
The connection to the WiFi is successful, the connection to the server is also correct, but when it try to use the server's websocket the following error occurs:
"Specified protocol was not requested by the client"

Also, as you will see in the screenshots, warnings are produced when compiling the arduino program.
Look at the following screenshots:

![sc19](https://user-images.githubusercontent.com/1523607/119122211-93734880-ba2e-11eb-821b-4d031b59fe46.jpg)

Server:
![sc17](https://user-images.githubusercontent.com/1523607/119122307-adad2680-ba2e-11eb-96e3-234e3f9f0c6f.jpg)

Client:
![sc18](https://user-images.githubusercontent.com/1523607/119122341-b56ccb00-ba2e-11eb-9efb-d568babbfbec.jpg)

Server Source code:

```
var WebSocketServer = require('websocket').server;
var http = require('http');

var server = http.createServer(function(request, response) {
    console.log((new Date()) + ' Received request for ' + request.url);
    response.writeHead(404);
    response.end();
});
server.listen(8080, function() {
    console.log((new Date()) + ' Server is listening on port 8080');
});

wsServer = new WebSocketServer({
    httpServer: server,
    // You should not use autoAcceptConnections for production
    // applications, as it defeats all standard cross-origin protection
    // facilities built into the protocol and the browser.  You should
    // *always* verify the connection's origin and decide whether or not
    // to accept it.
    autoAcceptConnections: false
});

function originIsAllowed(origin) {
  // put logic here to detect whether the specified origin is allowed.
  return true;
}

wsServer.on('request', function(request) {
    if (!originIsAllowed(request.origin)) {
      // Make sure we only accept requests from an allowed origin
      request.reject();
      console.log((new Date()) + ' Connection from origin ' + request.origin + ' rejected.');
      return;
    }
    
    var connection = request.accept('echo-protocol', request.origin);
    console.log((new Date()) + ' Connection accepted.');
    connection.on('message', function(message) {
        if (message.type === 'utf8') {
            console.log('Received Message: ' + message.utf8Data);
            connection.sendUTF(message.utf8Data);
        }
        else if (message.type === 'binary') {
            console.log('Received Binary Message of ' + message.binaryData.length + ' bytes');
            connection.sendBytes(message.binaryData);
        }
    });
    connection.on('close', function(reasonCode, description) {
        console.log((new Date()) + ' Peer ' + connection.remoteAddress + ' disconnected.');
    });
});
```
Any other tests you want me to do, you tell me.

Thank you.

**Comment by khoih-prog** [comment]
Good news that you can find your way out from now.

You can try this sophisticated [**SAMD_WiFi101-Client_SINRIC** example](https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/Generic/WiFi101/SAMD/SAMD_WiFi101-Client_SINRIC) and control your device from `Amazon's Alexa Voice control` and [**Sinric**](https://sinric.com/) or [**SinricPro**](https://sinric.pro/index.html) phone app.

For Spanish character issue, you have to ask on some forums how to solve as I don't have experience with `Internationalization`.

> Now I would have to try testing it with a normal websocket server, but I don't have any implementation.

You can use the [**SAMD_WiFi101-Server** example](https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/Generic/WiFi101/SAMD/SAMD_WiFi101-Server), or the similar one written for other boards, to create a test WebSocket Server.

**Comment by Josua2012** [comment]
However, for now I cannot use it with our server, since as I mentioned it works with **socket.io**.
Now, when you have made the compatibility of **WebSockets_Generic** I will test if it works with our server with nodejs + socket.io 

Very interesting what you tell me about control through Alexa and SinRic. I'll keep it in mind in case we need it. :)

To control an industrial encoder, speed measurement by sections, etc ... do you have any library recommendations?
Also, I have seen that you have very interesting libraries, if I want to prevent the sending of information to the server from interrupting in any way the data that is being received from the encoder, could one of your plugins be used for this? 

Thank you very much for all your help.

**Comment by khoih-prog** [comment]
> Now, when you have made the compatibility of WebSockets_Generic I will test if it works with our server with nodejs + socket.io

I'll put this in my very long bucket lists

1. WebSockets_Generic + WiFi101
2. WebSockets_Generic + Socket.IO

In the mean time, you can try to merge the code with [**Socket.IO-client** Library](https://github.com/timum-viw/socket.io-client) to see if OK.

> To control an industrial encoder, speed measurement by sections, etc ... do you have any library recommendations?

Try to use my [**SAMD_TimerInterrupt**](https://github.com/khoih-prog/SAMD_TimerInterrupt), especilly

1. [**ISR_RPM_Measure**](https://github.com/khoih-prog/SAMD_TimerInterrupt/tree/main/examples/ISR_RPM_Measure)
2. [**RPM_Measure**](https://github.com/khoih-prog/SAMD_TimerInterrupt/tree/main/examples/RPM_Measure)

These examples are using **ISR** and won't be interrupted by other low priority tasks.

**Comment by Josua2012** [comment]
Ahhh .... I thought you told me that by tomorrow you would have a version of **WebSockets_Generic + WiFi101**, that is what I had understood, for that reason I had been so happy, however, if it is not possible in all ways you I appreciate your efforts.

**Comment by khoih-prog** [comment]
Possibly I told you **WebSockets2_Generic + WiFi101**, not **WebSockets_Generic + WiFi101** as this is not in my mind at all. A typo (missing 2 ??)

**Comment by khoih-prog** [comment]
I'll try finish **WebSockets_Generic + WiFi101** next week as this is much simpler to do than last **WebSockets2_Generic + WiFi101**

**Comment by Josua2012** [comment]
Ohhh ... that would be wonderful ... thank you so much 👍

**Comment by khoih-prog** [comment]
i'm closing this issue now as there is nothing more to do here on this enhancement. 
Please open the new issue in [**WebSockets_Generic**](https://github.com/khoih-prog/WebSockets_Generic) to be consistent.
