### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by davekc** [khoih-prog/WebSockets2_Generic#24]
Hello, I get many compiler warnings using Teensy 4.1 and native ethernet. Even if everything works perfectly, it pollutes the compiler output and it is not really helpfull. Anything to do about it?

``[...]\Arduino\libraries\WebSockets2_Generic\src/Tiny_Websockets_Generic/message.hpp:58:6: warning: #warning WEBSOCKETS_USE_ETHERNET and USE_NATIVE_ETHERNET in client.hpp [-Wcpp]
     #warning WEBSOCKETS_USE_ETHERNET and USE_NATIVE_ETHERNET in client.hpp
      ^
In file included from [...]\Arduino\libraries\WebSockets2_Generic\src/Tiny_Websockets_Generic/message.hpp:59:0,
                 from [...]\Arduino\libraries\WebSockets2_Generic\src/WebSockets2_Generic.h:48,
                 from [...]\Arduino\web_server\web_server.ino:61:
[...]\Arduino\libraries\WebSockets2_Generic\src/Tiny_Websockets_Generic/internals/ws_common_NativeEthernet.hpp:59:8: warning: #warning Using NativeEthernet for Teensy 4.1 in ws_common_NativeEthernet.hpp [-Wcpp]
       #warning Using NativeEthernet for Teensy 4.1  in ws_common_NativeEthernet.hpp
        ^
In file included from [...]\Arduino\libraries\WebSockets2_Generic\src/WebSockets2_Generic.h:49:0,
                 from [...]\Arduino\web_server\web_server.ino:61:
[...]\Arduino\libraries\WebSockets2_Generic\src/Tiny_Websockets_Generic/client.hpp:64:6: warning: #warning WEBSOCKETS_USE_ETHERNET and USE_NATIVE_ETHERNET in client.hpp [-Wcpp]
     #warning WEBSOCKETS_USE_ETHERNET and USE_NATIVE_ETHERNET in client.hpp
      ^
In file included from [...]\Arduino\libraries\WebSockets2_Generic\src/WebSockets2_Generic.h:50:0,
                 from [...]\Arduino\web_server\web_server.ino:61:
[...]\Arduino\libraries\WebSockets2_Generic\src/Tiny_Websockets_Generic/server.hpp:59:6: warning: #warning WEBSOCKETS_USE_ETHERNET and USE_NATIVE_ETHERNET in server.hpp [-Wcpp]
     #warning WEBSOCKETS_USE_ETHERNET and USE_NATIVE_ETHERNET in server.hpp
      ^``

Thanks a lot for your work!

**Comment by khoih-prog** [comment]
Thanks for your interest in the library, hoping it's working well for you.

Those are **informational warnings** which are **intentionally** included to let users know what's happening with the configurations.

I have to use them in the library as there are **too many different settings** (boards, Ethernet / WiFi shields, etc), without information, it's difficult or impossible to know what wrong with the settings, etc.

If you're sophisticated user, you can know where the warnings are and just simply comment out those warning lines.
