### ISSUE TITLE
Loop function hangs even without the poll function

### ISSUE THREAD

**Issue by jackmerrill** [khoih-prog/WebSockets2_Generic#26]
Hi it's me again haha. When I run my code on the board, it only seems to run the loop function once, but if I remove / comment out any of the Websocket code, it works completely fine (lines 162 and 194).

Code: https://github.com/jackmerrill/FriendshipLamp/blob/main/Friendship_Lamp.ino

Here's how I know it doesn't loop:
```
23:11:39.759 -> Connnection Opened
23:11:39.759 -> Connected!
23:11:39.759 -> available
23:11:39.759 -> on
23:11:39.759 -> number of button pushes: 1
23:11:39.759 -> color
```

`available` and beyond should be printing more than just once.

Any and all help is appreciated, thanks!

**Comment by khoih-prog** [comment]
Sorry I have no time to help debug your complex use case.

I suggest you start with the [**SAMD-Client** example](https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/Generic/WiFiNINA/SAMD/SAMD-Client), then add more features gradually and see where / when the new code breaks.

I certainly won't have time to spend here unless you prove there is a reproducible bug of this library.

Good Luck,
