### ISSUE TITLE
WebSockets2_Generic on Mega2560 with w5100 ethernet shield

### ISSUE THREAD

**Issue by T2FF** [khoih-prog/WebSockets2_Generic#28]
Hello! 
Is it possible to run this library on a Mega2560 with w5100 ethernet shield?
I want to set up my Alexa Gateway with Sinric over Lan.

I cannot find a working example for my setup and always get a compatibility error ("This code is intended to run on...").

Thanks in Advance!

**Comment by khoih-prog** [comment]
As you've already tried and found out, too-old and resource-constraint Mega2560 **is and will not be supported.**

I suggest you use the more powerful and much cheaper **ESP32/ESP8266 or WT32_ETH01 (ESP32 + LAN8720)** for your purpose.

Good Luck,
