### ISSUE TITLE
Client IP address availability?

### ISSUE THREAD

**Issue by 5b4wn** [khoih-prog/WebSockets2_Generic#29]
Thanks for a great library

I cant seem to find the following anywhere.

I am using the  Teensy41_Server.ino  websocket server is it possible to have a method to get the websocket client's IP address please? Or is there any other way to do so?

Eg  client.remoteIP()  ?

This is useful for IP filtering etc.

Many thanks
Marios

**Comment by khoih-prog** [comment]
Thanks for your interest in and nice words about the library.

Currently, this library as well as its twin [WebSockets_Generic Library](https://github.com/khoih-prog/WebSockets_Generic), designed specifically for resource constraint MCUs, don't have that function to help in eliminate attacks, etc with the help of IP filtering.

You can have these options:

1. Use the Nodejs, etc. ws(s) server. Then the client IP is easily accessible. or example `ws._socket.remoteAddress`, `ws._socket.remotePort`

```
wss.on('connection', (ws, req) => 
{
    console.log(req.socket.remoteAddress);
});
```

2. Write extra code, based on (Native)Ethernet / WiFi, etc to capture the client IP.
3. Ask for enhancement (for ESP32/ESP8266) on [**ArduinoWebsockets** Library](https://github.com/gilmaimon/ArduinoWebsockets), on which this library is based on.

I'm sorry I currently have no time to work on this issue and closing it now. If there are many more similar requests,I'll possibly reopen and work on the issue.

Good Luck,
