### ISSUE TITLE
RobotDyn SamD21 M0 Zero compatible board

### ISSUE THREAD

**Issue by ericvb** [khoih-prog/WebSockets2_Generic#4]
I was testing the example in https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/Generic/Ethernet/SAMD/SAMD-Ethernet_AdvancedWebServer
but got nothing in the serial output.

These clone boards (https://www.aliexpress.com/item/32780674095.html?spm=a2g0s.9042311.0.0.27424c4dcsNo3b) are called Zero compatible, but don't have 2 USB ports like a real Zero (serial programming and serial USB).
The only port they have is the serial USB

So I had to add following code in the sketch example:
```
#if PLATFORM_ARCH == PLATFORM_ARCHITECTURE_SAMD21
#  define _SERIAL SerialUSB
#else
#  define _SERIAL Serial
#endif
```
and to use everywhere
`_SERIAL.println`

**Comment by khoih-prog** [comment]
Hi @ericvb 

Thanks for sharing your helpful experience to other users. 
As you know, there are too many boards, clones, etc. on the market, it's very difficult and time-consuming to take care of every one. The examples are just basic demonstration of the library's features, and you have to adapt it to meet your use-case demand.

Your feedback is appreciated and certainly will be used by other people.

Regards,
