### ISSUE TITLE
Error 1006 

### ISSUE THREAD

**Issue by ahdaib** [khoih-prog/WebSockets2_Generic#49]
I'm Using ESP8266-Client.ino Example and connected to this site  : https://socketsbay.com/test-websockets
i change 
in defines.h 
const char* websockets_server_host = "socketsbay.com"; //Enter server address
#define WEBSOCKETS_PORT   443    //8080

and in io file 
bool connected = client.connectSecure(websockets_server_host, websockets_server_port, "/wss/v2/2/demo/");

it's  work fine
but after 50 second the connection is close with code 1006 

can you test and check why the connection close with code 1006

Thank you

**Comment by khoih-prog** [comment]
Try the correct and **unmodified SSL** example, such as [**Secured-Esp8266-Client**](https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/ESP8266/Secured-Esp8266-Client) first to see if OK, then modify gradually for new WSS site.

You must do some more research on how TLS/SSL and to understand how to get correct SSL certificate / fingerprint, etc., not just blindly change the `site and port` of **non-SSL example**.

You already posted on

1. [**Error 1006 abnormal close websocket?**](https://forum.arduino.cc/t/error-1006-abnormal-close-websocket/1023950)
2. [ArduinoWebsockets issues](https://github.com/gilmaimon/ArduinoWebsockets/issues)

I'm closing the `invalid` issue now as this is not a proven bug of the library. **You'll be blocked to access** if continuing with unproven issues. It's more appropriate to post on Forum or Discussion session.

Good Luck,
