### ISSUE TITLE
Compile for Arduino Leonardo fails for missing STL

### ISSUE THREAD

**Issue by FalsinSoft** [khoih-prog/WebSockets2_Generic#5]
Hi

At first I would to say I'm new to Arduino world, that excuse me in advance if I made a mistake somewhere. Basically I have the Arduino Leonardo board with an ethernet shield with W5500 chip. I would to use your library to exchange data through WebSocket library but, using Visual Studio Code with platformio, I can't compile. The error refer to the include <string> file not found. Googling around I discovered that AVR compiler miss the STL support but after tried to add some alternative package for import STL I still receive errors because you code makes heavy use of the STL library. I tried to read all the tutorial here but I don't understand yet if I miss some steps or is not possible to use the library with Leonardo board.

Can you help me?

Thank you

**Comment by khoih-prog** [comment]
The Arduino AVR boards, such as Mega, UNO, Nano, **Leonardo**, etc. are not supported..

Please check and use the supported boards such as **Arduino SAMD21, Adafruit SAMD21/SAMD51, Seeeduino SAMD21/SAMD51, nRF52, STM32F/L/H/G/WB/MP1, Teensy, SAM DUE**
