### ISSUE TITLE
WebSockets2_Generic  example problem

### ISSUE THREAD

**Issue by dirkdickler** [khoih-prog/WebSockets2_Generic#52]
### 
In example : https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/Generic/Ethernet/ESP32/ESP32_Ethernet_ServerAllFunctionsDemo 

I have problem  with varialble: wsServer  - this varialbe not define in browser 
I create two server.on
server.on("/",     - problem  with varialble: wsServer   (orange,red)
server.on("/test" - (blue)  here I replace  text "new WebSocket(wsServer, ['arduino']); " 
          by my ipadress "new WebSocket(\"ws://192.168.1.10:8080/\", ['arduino']);" 
-result see in attachment

A testing on 
WebSockets2_Generic 1.12.0 and 1.12.1 latest  same result 
VS CODE -platformIO : 
espressif/toolchain-xtensa-esp32s2@ 8.4.0+2021r2-patch3
framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.5

![webSocket](https://user-images.githubusercontent.com/6540400/194942609-84ad3eb2-195d-4c3a-820e-76da3cba5cb5.png)

**Comment by khoih-prog** [comment]
Hi @dirkdickler 

> I have problem with varialble: wsServer - this varialbe not define in browser

https://github.com/khoih-prog/WebSockets2_Generic/blob/093b9f83f73ba6437f104a599dfedccad1c611fa/examples/Generic/Ethernet/ESP32/ESP32_Ethernet_ServerAllFunctionsDemo/ESP32_Ethernet_ServerAllFunctionsDemo.ino#L160

---

Try with that **unmodified** example first with **Arduino IDE**. If OK, then your code to see. If OK, then use more complex platform later, provided you know what's you're doing and with correct settings,

The example [**ESP32_Ethernet_ServerAllFunctionsDemo**](https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/Generic/Ethernet/ESP32/ESP32_Ethernet_ServerAllFunctionsDemo) is compiled here OK

![Selection_128](https://user-images.githubusercontent.com/57012152/194943900-d3c902b6-ec38-457a-be25-0e7e70839006.png)

---

Sorry if you still have issue with your code, please ask for support on **Arduino Forum** as I don't have time and not interested in helping with individual codes, unless there is a proven bug of the library.
