### ISSUE TITLE
RP2040W-Server example does not compile without errors

### ISSUE THREAD

**Issue by Hasenpups** [khoih-prog/WebSockets2_Generic#59]
Arduino IDE version: 2.0.2
Raspberry Pi Pico/RP2040 by Earle F. Philhower III Version: 2.6.4
WebSockets2_Generic by Gil Maimon, Khoi Hoang Version: 1.13.1
Raspberry Pi Pico W
OS: Windows 10

### Describe the bug

RP2040W-Server example does not compile without many warnings.

### Steps to Reproduce

Open RP2040W-Server example, select Raspberry Pi Pico W as board type and try to "Verify" the sketch

### Expected behavior

Example comiles without any warnings.

### Actual behavior

Severale compiler warnings occur. 

### Debug and AT-command log (if applicable)

`In file included from c:\Users\Stefan.Riese\Documents\Arduino\libraries\WebSockets2_Generic\src/WebSockets2_Generic.h:49,
                 from C:\Users\Stefan.Riese\AppData\Local\Temp\.arduinoIDE-unsaved2022115-14312-1awp9ql.a9d\RP2040W-Server\RP2040W-Server.ino:43:
c:\Users\Stefan.Riese\Documents\Arduino\libraries\WebSockets2_Generic\src/Tiny_Websockets_Generic/message.hpp:78:4: warning: #warning WEBSOCKETS_USE_RP2040W in message.hpp [-Wcpp]
   78 |   #warning WEBSOCKETS_USE_RP2040W in message.hpp
      |    ^~~~~~~
In file included from c:\Users\Stefan.Riese\Documents\Arduino\libraries\WebSockets2_Generic\src/Tiny_Websockets_Generic/message.hpp:79,
                 from c:\Users\Stefan.Riese\Documents\Arduino\libraries\WebSockets2_Generic\src/WebSockets2_Generic.h:49,
                 from C:\Users\Stefan.Riese\AppData\Local\Temp\.arduinoIDE-unsaved2022115-14312-1awp9ql.a9d\RP2040W-Server\RP2040W-Server.ino:43:
c:\Users\Stefan.Riese\Documents\Arduino\libraries\WebSockets2_Generic\src/Tiny_Websockets_Generic/internals/ws_common_RP2040W.hpp:55:4: warning: #warning Using RP2040W CYC43439 WIFI in ws_common_RP2040W.hpp [-Wcpp]
   55 |   #warning Using RP2040W CYC43439 WIFI in ws_common_RP2040W.hpp
      |    ^~~~~~~
c:\Users\Stefan.Riese\Documents\Arduino\libraries\WebSockets2_Generic\src/Tiny_Websockets_Generic/internals/ws_common_RP2040W.hpp:63:6: warning: #warning Using CYC43439 WIFI for RP2040W in ws_common_RP2040W.hpp [-Wcpp]
   63 |     #warning Using CYC43439 WIFI for RP2040W in ws_common_RP2040W.hpp
      |      ^~~~~~~
In file included from c:\Users\Stefan.Riese\Documents\Arduino\libraries\WebSockets2_Generic\src/WebSockets2_Generic.h:50,
                 from C:\Users\Stefan.Riese\AppData\Local\Temp\.arduinoIDE-unsaved2022115-14312-1awp9ql.a9d\RP2040W-Server\RP2040W-Server.ino:43:
c:\Users\Stefan.Riese\Documents\Arduino\libraries\WebSockets2_Generic\src/Tiny_Websockets_Generic/client.hpp:86:4: warning: #warning WEBSOCKETS_USE_RP2040W in client.hpp [-Wcpp]
   86 |   #warning WEBSOCKETS_USE_RP2040W in client.hpp
      |    ^~~~~~~
In file included from c:\Users\Stefan.Riese\Documents\Arduino\libraries\WebSockets2_Generic\src/WebSockets2_Generic.h:51,
                 from C:\Users\Stefan.Riese\AppData\Local\Temp\.arduinoIDE-unsaved2022115-14312-1awp9ql.a9d\RP2040W-Server\RP2040W-Server.ino:43:
c:\Users\Stefan.Riese\Documents\Arduino\libraries\WebSockets2_Generic\src/Tiny_Websockets_Generic/server.hpp:79:4: warning: #warning WEBSOCKETS_USE_RP2040W in server.hpp [-Wcpp]
   79 |   #warning WEBSOCKETS_USE_RP2040W in server.hpp
      |    ^~~~~~~
Sketch uses 347068 bytes (16%) of program storage space. Maximum is 2093056 bytes.
Global variables use 68204 bytes (26%) of dynamic memory, leaving 193940 bytes for local variables. Maximum is 262144 bytes.
`

### Screenshots

N/A

**Comment by khoih-prog** [comment]
HI @Hasenpups 

> Sketch uses 347068 bytes (16%) of program storage space. Maximum is 2093056 bytes. Global variables use 68204 bytes (26%) of dynamic memory, leaving 193940 bytes for local variables. Maximum is 262144 bytes.

Those are informational warnings so that you know what you're doing and to be ignored. Not errors as you **incorrectly** mentioned.

Don't waste anybody time by this kind of nonsense.
