### ISSUE TITLE
Multiple Clients Teensy41 server example QNEthernet

### ISSUE THREAD

**Issue by videojedi** [khoih-prog/WebSockets2_Generic#65]
HI,
When trying to run the following example, my teensy seems to get stuck in a loop of accepting new websocket client connections. I don't quite understand what is happening. I'm using the latest build of QNEthernet. Doesn't seem to happen with  Native Ethernet.
Possibly didn't happen on versions prior to latest release?

https://github.com/khoih-prog/WebSockets2_Generic/blob/master/examples/Generic/Teensy41_QNEthernet/MultipleClients_Teensy41_Server/MultipleClients_Teensy41_Server.ino

Terminal output is

Accepted new websockets client at index 0
Accepted new websockets client at index 0
Accepted new websockets client at index 0
Accepted new websockets client at index 0
Accepted new websockets client at index 0
Accepted new websockets client at index 0
...

Arduino IDE version: 1.8.19
Teensy4.1
QNEthernet  0.17.0
Windows 10

Many thanks
Richard.

**Comment by khoih-prog** [comment]
Hi @videojedi 

Just comment out the unnecessary line

https://github.com/khoih-prog/WebSockets2_Generic/blob/3dd5c9f98470b1a0e445c62a3535934e83aec72d/examples/Generic/Teensy41_QNEthernet/MultipleClients_Teensy41_Server/MultipleClients_Teensy41_Server.ino#L253

Be sure to have the client connect to the same IP:port

Tested OK for

#### QNEthernet v0.14.0

```
Starting MultiClients_Teensy41_Server on TEENSY 4.1 using QNEthernet
WebSockets2_Generic v1.13.2
=========== USE_QN_ETHERNET ===========
Initialize Ethernet using DHCP => IP Address = 192.168.2.119
Server available at ws://192.168.2.119:8080
Got Message: Hello to Server from ESP32
Connection closed
Got Message: Hello to Server from ESP32
Connection closed
Got Message: Hello to Server from ESP32
Connection closed
Got Message: Hello to Server from ESP32
```

#### QNEthernet v0.17.0

```
Starting MultiClients_Teensy41_Server on TEENSY 4.1 using QNEthernet
WebSockets2_Generic v1.13.2
=========== USE_QN_ETHERNET ===========
Initialize Ethernet using DHCP => IP Address = 192.168.2.119
Server available at ws://192.168.2.119:8080
Got Message: Hello to Server from ESP32
Connection closed
Got Message: Hello to Server from ESP32
```
